### ISSUE TITLE
Unable to Factory Reset or Update to G.2.2

### ISSUE THREAD

**Issue by bperseghetti** [iRobotEducation/create3_docs#113]
I am unable to Factory Reset or update from G.1.1 whether connected in AP or connected to local wifi.

When connected in AP mode the FW upload fails, and when connected to wifi
 network it fails to update as well.

Also under the about section when I connect in AP or any other mode it seems odd that it shows: 

SYSTEM_ACCESS : locked
DEVELOPMENT MODE : disabled

@shamlian Any advice would be appreciated.

**Comment by shamlian** [comment]
This might be one best solved directly. Could you email create@irobot.com, and we'll try to figure out what's going on?
