### ISSUE TITLE
Create 3 discussion forum?

### ISSUE THREAD

**Issue by slowrunner** [iRobotEducation/create3_docs#2]
Could you all add a link on the create3_docs/README.md to a Create3 discussion forum?
Or "Where to post questions"  (create3@irobot.com?    robotics.stackexchange.com?)

It would sure be nice to have a dedicated create3 Q&A place.

**Comment by shamlian** [comment]
[Discussions](https://github.com/iRobotEducation/create3_docs/discussions) is now enabled. Thanks for the suggestion!
