### ISSUE TITLE
Create3 stuck in boot loop

### ISSUE THREAD

**Issue by Marwan-Refaat** [iRobotEducation/create3_docs#201]
### Discussed in https://github.com/iRobotEducation/create3_docs/discussions/200

<div type='discussions-op-text'>

<sup>Originally posted by **Marwan-Refaat** September 17, 2022</sup>
**Overview:**
While setting up my create3 robots, they got stuck in a boot loop. The lightring is displaying the pattern that corresponds to booting up (white spinning animation). When trying to cycle power, they turn off for less than a second and start the booting animation again. 

Is there a way to possibly do a factory reset?

**Details:**
I was setting up 9 Create3 robots. I followed the directions for the setup guide (https://edu.irobot.com/create3-setup). I connected to each robot's hotspot, updated the robots' firmware, and waited for them to boot again. 

The issue started when trying to connect them to wifi. After trying to connect them to wifi, the robots' lightring turned a solid red color. Following the directions from the docs (https://iroboteducation.github.io/create3_docs/hw/face/), I cycled their power by holding the power button for 20 seconds until they turned off and on again. From this point on, the robots have been stuck in the booting sequence (lightring displaying a spinning white animation). 

 It is worth noting that this only occurred for 5 of the 9 robots, the other 4 robots are booting up successfully and connecting to wifi (This was verified by using `ros2 topic list`). It is also worth noting that I set separate ROS_DOMAIN_ID and ROS_NAMESPACE variables for each robot I was setting up, but I am not certain the changes were actually saved for all 9 of the robots. 

**Actions taken:**
- I have tried cycling power by holding the power button for 20 seconds, which just turns off the robot for less than a second, then turns on again and continues the same booting animation

- I have tried holding the two user interface buttons to turn on the robot's hotspot to no avail.

- I have tried switching the Bluetooth/USB switch on the robots to the USB setting and tried connecting to the webserver through USB to no avail as well.

- I have also tried looking for ways to possibly do a "hard" reset or factory reset, but I was not able to find any sources online for that.

**Any suggestions on possible fixes are highly appreciated.**

</div>

**Comment by shamlian** [comment]
Discussion in progress; suggested emailing iRobot support as well.
