### ISSUE TITLE
Generate a list of all names of the specific Create 3 open source GPL components for source code requests

### ISSUE THREAD

**Issue by MAVProxyUser** [iRobotEducation/create3_docs#225]
In order to get GPL source code your company forces me to provide a list of component names... so you can charge me $5 per component. 

https://github.com/iRobotEducation/create3_docs/issues/221#issuecomment-1278000817

Please use the Yocto Linux GPL compliance scripts to generate a list of said components and share it with the community so that we may make the requests in the format you require. We can't possibly know all the components you use because you are treating the system as *closed*. 

https://github.com/iRobotEducation/create3_docs/issues/222

You've created a bad faith stop gap, and gate keeping method as a means to hide the open source internals of your product. Please assist the community in confirming to your unrealistic wishes so that we may access the source code. 

In fact please provide a list of ALL components for ALL iRobot models so that an exhaustive request can be made.

**Comment by Alex-Kw** [comment]
Let us have a look at a couple sections of the GPL:

`6. Conveying Non-Source Forms.

  You may convey a covered work in object code form under the terms
of sections 4 and 5, provided that you also convey the
machine-readable Corresponding Source under the terms of this License,
in one of these ways:

    a) Convey the object code in, or embodied in, a physical product
    (including a physical distribution medium), accompanied by the
    Corresponding Source fixed on a durable physical medium
    customarily used for software interchange.

    b) Convey the object code in, or embodied in, a physical product
    (including a physical distribution medium), accompanied by a
    written offer, valid for at least three years and valid for as
    long as you offer spare parts or customer support for that product
    model, to give anyone who possesses the object code either (1) a
    copy of the Corresponding Source for all the software in the
    product that is covered by this License, on a durable physical
    medium customarily used for software interchange, for a price no
    more than your reasonable cost of physically performing this
    conveying of source, or (2) access to copy the
    Corresponding Source from a network server at no charge.

    c) Convey individual copies of the object code with a copy of the
    written offer to provide the Corresponding Source.  This
    alternative is allowed only occasionally and noncommercially, and
    only if you received the object code with such an offer, in accord
    with subsection 6b.

    d) Convey the object code by offering access from a designated
    place (gratis or for a charge), and offer equivalent access to the
    Corresponding Source in the same way through the same place at no
    further charge.  You need not require recipients to copy the
    Corresponding Source along with the object code.  If the place to
    copy the object code is a network server, the Corresponding Source
    may be on a different server (operated by you or a third party)
    that supports equivalent copying facilities, provided you maintain
    clear directions next to the object code saying where to find the
    Corresponding Source.  Regardless of what server hosts the
    Corresponding Source, you remain obligated to ensure that it is
    available for as long as needed to satisfy these requirements.

    e) Convey the object code using peer-to-peer transmission, provided
    you inform other peers where the object code and Corresponding
    Source of the work are being offered to the general public at no
    charge under subsection 6d.`
    
    `  10. Automatic Licensing of Downstream Recipients.

  Each time you convey a covered work, the recipient automatically
receives a license from the original licensors, to run, modify and
propagate that work, subject to this License.  You are not responsible
for enforcing compliance by third parties with this License.`

This seems rather straightforward; provide the open source software being used under GPL as obligated. Charging per item per disc seems like a stall tactic on the surface; in the modern world, it should not be a burden to produce code that is being used under a license which requires such an ability.  Section 6b(1) says -all- software covered by this license (GPL) should be provided, so it is arguable that charging for separate copies of media for each piece of GPL software would be a violation in and of itself.

**Comment by MAVProxyUser** [comment]
Oh man... the crows sure came home to roost here eh!? Have the security and legal team re-watch this talk from Patrick Doyle in full, from this point on: https://youtu.be/t54T9uemiRU?t=1662

**Comment by MAVProxyUser** [comment]
Closed out here: https://github.com/iRobotEducation/create3_docs/issues/221#issuecomment-1287326822
