### ISSUE TITLE
Update CycloneDDS instructions

### ISSUE THREAD

**Issue by thijsmie** [iRobotEducation/create3_docs#228]
Hi there!

I am a committer of the Eclipse CycloneDDS project and I've noticed some out of date information on your website. I made some updates to it on my fork, but I am not allowed to make a PR for some reason. They are here:

https://github.com/thijsmie/irobot_education_create3_docs

**Comment by alsora** [comment]
Thank you for your contribution!
I'm not sure why you can't open a pull request.
I took the liberty to open it for you https://github.com/iRobotEducation/create3_docs/pull/229

**Comment by shamlian** [comment]
Fixed with #442
