### ISSUE TITLE
Electrical TOC not rendering properly 

### ISSUE THREAD

**Issue by alsora** [iRobotEducation/create3_docs#24]
![Screenshot from 2022-02-17 17-53-06](https://user-images.githubusercontent.com/25433200/154541482-9365da9b-ea35-4738-a1b0-0014af16182d.png)

This is the table of content in the Hardware -> Electrical page.
Only one indicator renders properly

**Comment by alsora** [comment]
I usually use Chromium on Ubuntu 20.04.
It does not render in standard Google Chrome either.

I tired with firefox and it renders properly there.

**Comment by shamlian** [comment]
Interesting; I am using Chrome on Windows 10 (v98.0.4758.82) and it's rendering. Can you go [here ](https://unicode.org/emoji/charts-12.1/emoji-ordering-rules.txt)and tell me what you see?

**Comment by shamlian** [comment]
I'm sorry that this seems like a system configuration problem, not a problem with the docs site.

**Comment by alsora** [comment]
For what is worth I see the same thing in Chrome, version 97.0.4692.71

**Comment by shamlian** [comment]
I am open to removing emoji from the docs site, or taking them out of the TOC and adding them to the body with a note that they may not render if you're not up to the most recent Unicode.

**Comment by shamlian** [comment]
I think maybe we should decide on a minimum Unicode version to support. Here are the release dates: https://unicode.org/history/publicationdates.html

**Comment by shamlian** [comment]
@alsora just for our knowledge, can you see the following:
Added in Unicode 12: 🦩
Added in Unicode 11: 🦡
Added in Unicode 10: 🦔
Added in Unicode 9: 🦐
Added in Unicode 8: 🦄
Added in Unicode 7: 🐿
