### ISSUE TITLE
E: Unable to locate package ros-galactic-ros-base 

### ISSUE THREAD

**Issue by jungseokhong** [iRobotEducation/create3_docs#288]
I ran the following commands to install inside docker image. However,I wasn't able to locate the pakages.

sudo apt update && sudo apt install -y ros-galactic-ros-base python3-colcon-common-extensions python3-rosdep ros-galactic-rmw-fastrtps-cpp ros-galactic-rmw-cyclonedds-cpp ros-galactic-irobot-create-msgs

any suggestions?

**Comment by c1505** [comment]
@jungseokhong did you find a solution here ? I have the same issue after following the instructions.
