### ISSUE TITLE
Feature request: Cliff Sensor Intensity Values

### ISSUE THREAD

**Issue by shamlian** [iRobotEducation/create3_docs#320]
### Discussed in https://github.com/iRobotEducation/create3_docs/discussions/319

<div type='discussions-op-text'>

<sup>Originally posted by **Kola50011** January 24, 2023</sup>
Hey! 
I am working on a project, where we would like to detect a black line on the floor using the 4 cliff sensors. Sadly, this information not published by the ROS API. Is there any way to access such information, other than the _/hazard_detection_ topic? We  would greatly appreciate something similar to the _/ir_intensity_ topic.</div>

**Comment by Kola50011** [comment]
Hello, I saw that this feature was removed from H.1.0 - any plans when this might be added? I would really appreciate native support instead of having a workaround and mounting my own, additional sensors to the robot.

**Comment by shamlian** [comment]
Hi @Kola50011! Not to worry, this feature is still in development. As soon as there is a planned release, I will let you know via this issue.

**Comment by fmorshed52** [comment]
What is the ETA on this feature?

Thank you,

**Comment by shamlian** [comment]
It is the team's intention to release this very soon.
