### ISSUE TITLE
Improve configurability of NTP sync sources

### ISSUE THREAD

**Issue by shamlian** [iRobotEducation/create3_docs#333]
As an end user it would be helpful to edit the chrony.conf file on the create3, using a similar process as the "Application ROS2 Parameter File". So that we can configure the create3 to directly source from a local ntp time server.

_Originally posted by @Jayden-F in https://github.com/iRobotEducation/create3_docs/issues/327#issuecomment-1428869938_

**Comment by Jayden-F** [comment]
@shamlian How is this going?
