### ISSUE TITLE
Add the option to change the static usb0 subnet

### ISSUE THREAD

**Issue by roni-kreinin** [iRobotEducation/create3_docs#335]
Currently it is not possible to run multiple TurtleBot 4's using discovery server with one remote PC because all Create 3's have the same `usb0` IP. The PC cannot create multiple ip routes to `192.168.186.0/24`. Adding the option to change the subnet to a unique value (i.e. `192.168.187.0`) using the webserver should solve this issue. The IP address should probably still be forced to xxx.xxx.xxx.2.

**Comment by Jayden-F** [comment]
@shamlian there seems to so many roadblocks for getting multiple turtlebot4 working on a single network. Could you please look into this and let us know if it can be resolved?

**Comment by shamlian** [comment]
The team is looking into this (and other network requests) now.

**Comment by shamlian** [comment]
To avoid any further delay, I've added this as a beta feature as part of a patch release (G.4.5 / H.1.2).
