### ISSUE TITLE
Wi-Fi connectivity issues

### ISSUE THREAD

**Issue by roni-kreinin** [iRobotEducation/create3_docs#395]
There are a couple of TurtleBot 4 users who have run into various issues with connecting the Create 3 to Wi-Fi. I would appreciate any insight into what could be causing these problems.

- https://github.com/turtlebot/turtlebot4/issues/183
- https://github.com/turtlebot/turtlebot4/issues/175

**Comment by shamlian** [comment]
We have released G.5.3 and H.2.3 to correct a bug in the provisioning workflow; users encountering a problem should update their firmware and then redo the connection workflow (go to the Connect page and put in SSID/pass/region). Please re-open this ticket if the problem is not resolved.
