### ISSUE TITLE
Web Server: Address of Fast DDS discovery server does NOT accept special characters

### ISSUE THREAD

**Issue by royito55** [iRobotEducation/create3_docs#400]
Hi,

I found an issue while attempting to communicate 2 create3's (with a RPi4) with another PC. 

In order to connect to both robots from another PC, the discovery servers must be run on different IDs. 

This means that the nodes running from one of the create3 must have the variable `ROS_DISCOVERY_SERVER=;192.168.186.3:11811` (note the preceding `;`). Refer to DDS docs [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/env_vars/env_vars.html#env-vars-ros-discovery-server) and to my discussion with @EduPonz [here](https://github.com/eProsima/Fast-DDS/discussions/3560#discussioncomment-6077189).

However, when I try to add this in the web server App config, I get the message "Please set a valid ipv4 address and port for the discovery server."
![envvar](https://github.com/iRobotEducation/create3_docs/assets/26725409/f5609a80-5aa7-4651-bdb7-4a0aa8006ece)

Can this be changed so special characters are allowed in that field?

Thank you

**Comment by EduPonz** [comment]
Thanks @royito55! @alsora could you please point to the correct person to address this?

**Comment by alsora** [comment]
I don't have a lot of context on the discovery server, but this seems a fairly straight-forward change.
We have a new firmware that will be released soon and we can make this change there.

**Comment by EduPonz** [comment]
Basically, adding `;` as an allowed character there will allow for:
1. Connecting the create3 to several Discovery Servers
2. Connecting the create3 to Discovery Servers with ID other than 0

My guess is that is a simple change on the input validation, but I cannot be sure of course.

**Comment by alsora** [comment]
Yes, there's a regex in there and I just added the `;` character.

I'll let you know as soon as the new firmware is publicly available.
