### ISSUE TITLE
Major TF errors: `/tf` and `/tf_static` should not be namespaced, TF tree wrong.

### ISSUE THREAD

**Issue by royito55** [iRobotEducation/create3_docs#402]
Three major TF related issues that prevent proper use with ROS 2:

1. When a namespace is added to the web server app config, it applies a namespace to all of the topics that the robot offers, including `/tf` and `/tf_static`. This is wrong, all robots should publish to a single `/tf`/`tf_static` topic, not something like `robot_N/tf`.
2. The messages in the topics themselves should have the namespace applied in the web server app config. So, for example, it shouldn't be topic  `robot_N/tf` containing a `odom -> base_link` message, but rather topic `/tf` containing a `robot_N/odom -> robot_N/base_link` message, one for each robot.
This can be solved by adding a xacro tag in the URDF file that the robot description is loading. The tag would be a variable for the robot namespace, and if there is no namespace required, then the xacro tag is empty.
3. The TF tree is wrong. The `odom` frame should not have 2 children (`base_footprint` and `base_link`), it should only have `base_footprint`, so it should be `odom`->`base_footprint`->`base_link`. This can also be solved in the URDF

This is a simple fix that would take the create3 a loong way in usability, @alsora maybe this could also be included in the next firmware update?

**Comment by royito55** [comment]
Thank you so much for responding so fast.

I understand, I didn't know there was no specification and I was going off of previous multi robot setups.

**Comment by ipa-rar** [comment]
@alsora @royito55  You can use [tf_relay](https://github.com/ipa-rar/tf_relay) package for now. Developed for internal use but this is useful whenever you have to use namspace with TB4 or create3 base. Hope it helps

**Comment by royito55** [comment]
@ipa-rar nice! I was trying to make my own, thanks for the link!
