### ISSUE TITLE
Enhancement: Allow users to set XML config files for DDS

### ISSUE THREAD

**Issue by royito55** [iRobotEducation/create3_docs#407]
I think it would be great to be able to set XML configuration files for the create3, both for Fast-DDS and CycloneDDS. This allows for more flexibility while setting up multi-robot networking, like specifying domain participants, UDPv4/v6, etc:

https://fast-dds.docs.eprosima.com/en/latest/fastdds/xml_configuration/xml_configuration.html

**Comment by alsora** [comment]
Hi, we already developed this feature for Fast-DDS and it's going to be included in the next release.

**Comment by royito55** [comment]
Awesome! it would also be incredible if we could monitor the DDS network with Vulcanexus Fast-DDS monitor (some environment variables are needed before launching create3 nodes: https://docs.vulcanexus.org/en/latest/rst/tutorials/tools/fastdds_monitor/fastdds_monitor.html
