### ISSUE TITLE
Bad links on Install ROS 2 Humble with Create 3 Messages on an Ubuntu 22.04 Machine

### ISSUE THREAD

**Issue by jomoengineer** [iRobotEducation/create3_docs#528]
There are links on the page for "Install ROS 2 Humble with Create 3 Messages on an Ubuntu 22.04 Machine" that are showing a 404 error.
Page
[https://github.com/iRobotEducation/create3_docs/blob/main/docs/setup/ubuntu2204.md](url)

Ex:
More detail on RMW can be found [here](https://github.com/iRobotEducation/create3_docs/blob/main/docs/xml-config)

If this does not work, please refer to [ROS 2 Network Configuration](https://github.com/iRobotEducation/create3_docs/blob/main/docs/xml-config) for further configuration ideas. A full Create® 3 API description can be found [here](https://github.com/iRobotEducation/create3_docs/blob/main/api/ros2).

**Comment by shamlian** [comment]
On it!

**Comment by shamlian** [comment]
The links are fine -- the problem is that you are accessing the _source_ of the docs site instead of the docs site itself. Try https://iroboteducation.github.io/create3_docs/setup/ubuntu2204/

**Comment by jomoengineer** [comment]
Ah, got it. thanks
